package JFrames;

import RegistrarIngreso.GestorFinanzas;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author familia4
 */
public class MenuRegistrarIngresos extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuRegistrarIngresos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngresos = new javax.swing.JTable();
        Agregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Editar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Ingresos = new javax.swing.JButton();
        Retroceder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        tablaIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "monto", "categoria", "fecha"
            }
        ));
        jScrollPane1.setViewportView(tablaIngresos);

        Agregar.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ingreso4.png"))); // NOI18N

        Editar.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        Editar.setText("Editar");
        Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Editar)
                        .addGap(82, 82, 82)
                        .addComponent(Eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Agregar)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Editar)
                                .addComponent(Eliminar))
                            .addComponent(Agregar))
                        .addGap(29, 29, 29)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setText("Administrador de Finanzas Personal");

        Ingresos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Ingresos.setText("Ingresos");
        Ingresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresosActionPerformed(evt);
            }
        });

        Retroceder.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        Retroceder.setText("Retroceder");
        Retroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetrocederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(Ingresos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Retroceder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(Ingresos)
                .addGap(43, 43, 43)
                .addComponent(Retroceder)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresosActionPerformed

        // Crear una instancia de GestorFinanzas
        GestorFinanzas gestor = new GestorFinanzas();

        // Obtener la lista de ingresos desde la base de datos
        List<Object[]> ingresos = gestor.obtenerIngresos();

        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tablaIngresos.getModel();

        // Limpiar la tabla antes de cargar nuevos datos
        model.setRowCount(0);

        // Añadir los ingresos al modelo de la tabla
        for (Object[] ingreso : ingresos) {
            model.addRow(ingreso);
        }
    }//GEN-LAST:event_IngresosActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed

        // Crear una instancia del formulario secundario
        RegistrarIngreso EditarIngresos = new RegistrarIngreso();

        // Hacer visible el formulario secundario
        EditarIngresos.setVisible(true);
    }//GEN-LAST:event_AgregarActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed

        // Obtener la fila seleccionada
    int filaSeleccionada = tablaIngresos.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tablaIngresos.getModel();

        // Obtener los valores actuales
        Object idObj = model.getValueAt(filaSeleccionada, 0); // id
        Object montoObj = model.getValueAt(filaSeleccionada, 1); // monto
        Object categoriaObj = model.getValueAt(filaSeleccionada, 2); // categoría
        Object fechaObj = model.getValueAt(filaSeleccionada, 3); // fecha

        // Pedir nuevos valores al usuario
        String nuevoMontoStr = javax.swing.JOptionPane.showInputDialog(this, "Nuevo monto:", montoObj);
        String nuevaCategoria = javax.swing.JOptionPane.showInputDialog(this, "Nueva categoría:", categoriaObj);
        String nuevaFechaStr = javax.swing.JOptionPane.showInputDialog(this, "Nueva fecha (YYYY-MM-DD):", fechaObj.toString());

        // Validar que los valores no sean nulos
        if (nuevoMontoStr != null && nuevaCategoria != null && nuevaFechaStr != null) {
            try {
                // Convertir los valores a los tipos correctos
                double nuevoMonto = Double.parseDouble(nuevoMontoStr);
                LocalDate nuevaFecha = LocalDate.parse(nuevaFechaStr);  // Convertir la fecha

                // Actualizar los valores en la tabla localmente
                model.setValueAt(nuevoMonto, filaSeleccionada, 1); // Actualizar monto en la tabla
                model.setValueAt(nuevaCategoria, filaSeleccionada, 2); // Actualizar categoría en la tabla

                // Convertir LocalDate a java.sql.Date
                java.sql.Date sqlDate = java.sql.Date.valueOf(nuevaFecha);
                model.setValueAt(sqlDate, filaSeleccionada, 3); // Actualizar fecha en la tabla

                // Actualizar la base de datos
                GestorFinanzas gestor = new GestorFinanzas();
                gestor.actualizarIngreso((int) idObj, nuevoMonto, nuevaCategoria, nuevaFecha);

                javax.swing.JOptionPane.showMessageDialog(this, "Ingreso actualizado correctamente.");

            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Formato de monto incorrecto.");
            } catch (DateTimeParseException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Usa YYYY-MM-DD.");
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para editar.");
    }
    }//GEN-LAST:event_EditarActionPerformed

    private void RetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetrocederActionPerformed
        // Crear una instancia del formulario secundario
        Menu IrMenu = new Menu();  //Se cambia el Menu

        // Hacer visible el formulario secundario
        IrMenu.setVisible(true);
    }//GEN-LAST:event_RetrocederActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        // Obtener la fila seleccionada
    int filaSeleccionada = tablaIngresos.getSelectedRow();

    if (filaSeleccionada != -1) {
        // Obtener el modelo de la tabla
        DefaultTableModel model = (DefaultTableModel) tablaIngresos.getModel();

        // Obtener el id del registro a eliminar (la primera columna)
        Object idObj = model.getValueAt(filaSeleccionada, 0);

        // Confirmar antes de eliminar
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Estás seguro de que deseas eliminar este ingreso?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // Eliminar el registro de la base de datos
            try {
                GestorFinanzas gestor = new GestorFinanzas();
                gestor.eliminarIngreso((int) idObj); // Pasar el id al método eliminarIngreso

                // Eliminar la fila de la tabla visual
                model.removeRow(filaSeleccionada);

                javax.swing.JOptionPane.showMessageDialog(this, "Ingreso eliminado correctamente.");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el ingreso.");
                e.printStackTrace();
            }
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecciona una fila para eliminar.");
    }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrarIngresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuRegistrarIngresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Ingresos;
    private javax.swing.JButton Retroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaIngresos;
    // End of variables declaration//GEN-END:variables
}
