/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

import ClaseDAO.CategoriaGastoDAO;
import ClaseDAOImpl.CategoriaGastoDAOImpl;
import Clases.CategoriaGasto;
import ConexionBD.ConexionDB;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Luan Condori
 */
public class EstablecerPresupuesto extends javax.swing.JFrame {
     private static final Logger logger = Logger.getLogger(EstablecerPresupuesto.class.getName());  // Inicializa el logger
    private CategoriaGastoDAO categoriaGastoDAO;
    private Connection conexion;
    /**
     * Creates new form EstablecerPresupuesto
     */
    public EstablecerPresupuesto() {
        initComponents();
        this.conexion = ConexionDB.getConexion(); // Conexión a la base de datos
        this.categoriaGastoDAO = new CategoriaGastoDAOImpl(conexion);
        establecerPresupuesto(); // Llamar al método para cargar los datos en los JLabels
    
    }
     private void establecerPresupuesto() {
        // Establecer las asignaciones de las categorías de gasto en los JLabels
        logger.info("Estableciendo presupuesto...");
        setCategoriaAsignacionEnLabel(1, txt1Alimentacion);
        setCategoriaAsignacionEnLabel(2, txt1DeudasPrestamos);
        setCategoriaAsignacionEnLabel(3, txt1DonacionesRegalos);
        setCategoriaAsignacionEnLabel(4, txt1Educacion);
        setCategoriaAsignacionEnLabel(5, txt1Entretenimiento);
        setCategoriaAsignacionEnLabel(6, txt1RopaYaccesorios);
        setCategoriaAsignacionEnLabel(7, txt1Salud);
        setCategoriaAsignacionEnLabel(8, txt1Transporte);
        setCategoriaAsignacionEnLabel(9, txt1Vivienda);
        logger.info("Presupuesto establecido correctamente.");
    }

    private void setCategoriaAsignacionEnLabel(int idCategoria, JLabel label) {
        // Obtener la categoría de gasto por ID
        logger.info("Obteniendo categoría de gasto con ID: " + idCategoria);
        CategoriaGasto categoriaGasto = categoriaGastoDAO.obtenerPorId(idCategoria);
        
        // Si la categoría de gasto es válida, setear su asignación en el JLabel
        if (categoriaGasto != null) {
            logger.info("Categoría encontrada: " + categoriaGasto.getNombre() + ", asignación: " + categoriaGasto.getAsignacion());
            label.setText("S/ " + categoriaGasto.getAsignacion());
        } else {
            // Si la categoría no se encuentra, mostrar un mensaje de error
            logger.warning("No se encontró la categoría de gasto con ID: " + idCategoria);
            label.setText("No disponible");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAlimentacion = new javax.swing.JTextField();
        txtTransporte = new javax.swing.JTextField();
        txtVivienda = new javax.swing.JTextField();
        txtSalud = new javax.swing.JTextField();
        txtEntretenimiento = new javax.swing.JTextField();
        txtEducacion = new javax.swing.JTextField();
        txtRopa = new javax.swing.JTextField();
        txtDeudas = new javax.swing.JTextField();
        txtRegalos = new javax.swing.JTextField();
        bntModificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt1Alimentacion = new javax.swing.JLabel();
        txt1Transporte = new javax.swing.JLabel();
        txt1Vivienda = new javax.swing.JLabel();
        txt1Salud = new javax.swing.JLabel();
        txt1Entretenimiento = new javax.swing.JLabel();
        txt1Educacion = new javax.swing.JLabel();
        txt1RopaYaccesorios = new javax.swing.JLabel();
        txt1DeudasPrestamos = new javax.swing.JLabel();
        txt1DonacionesRegalos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Establecer Presupuesto");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setText("Alimentacion");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setText("Transporte");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setText("Vivienda");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setText("Salud");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setText("Entretenimiento");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setText("Educacion");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setText("Ropa");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Deudas");

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setText("Regalos");

        txtAlimentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlimentacionActionPerformed(evt);
            }
        });

        bntModificar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        bntModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/editar.png"))); // NOI18N
        bntModificar.setText("Modificar");
        bntModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModificarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Regresar Registros.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("ValorActual");

        txt1Alimentacion.setText("s/.");

        txt1Transporte.setText("s/.");

        txt1Vivienda.setText("s/.");

        txt1Salud.setText("s/.");

        txt1Entretenimiento.setText("s/.");

        txt1Educacion.setText("s/.");

        txt1RopaYaccesorios.setText("s/.");

        txt1DeudasPrestamos.setText("s/.");

        txt1DonacionesRegalos.setText("s/.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtVivienda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtSalud, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTransporte)
                                    .addComponent(txtAlimentacion)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDeudas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(txtRopa, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEducacion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtEntretenimiento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtRegalos))))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt1Alimentacion)
                            .addComponent(txt1Transporte)
                            .addComponent(txt1Vivienda)
                            .addComponent(txt1Salud)
                            .addComponent(txt1Entretenimiento)
                            .addComponent(txt1Educacion)
                            .addComponent(txt1RopaYaccesorios)
                            .addComponent(txt1DeudasPrestamos)
                            .addComponent(txt1DonacionesRegalos))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(bntModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAlimentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Alimentacion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Transporte))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Vivienda))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Salud))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEntretenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Entretenimiento))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEducacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1Educacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1RopaYaccesorios))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDeudas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt1DeudasPrestamos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(txtRegalos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt1DonacionesRegalos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntModificar)
                    .addComponent(btnRegresar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAlimentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlimentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlimentacionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void bntModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificarActionPerformed
try {
    Logger logger = Logger.getLogger("CategoriaGastoUpdater");

    // Registrar inicio de la operación
    logger.info("Iniciando actualización de categorías de gasto.");

    double alimentacion = Double.parseDouble(txtAlimentacion.getText());
    double deudas = Double.parseDouble(txtDeudas.getText());
    double educacion = Double.parseDouble(txtEducacion.getText());
    double entretenimiento = Double.parseDouble(txtEntretenimiento.getText());
    double regalos = Double.parseDouble(txtRegalos.getText());
    double ropa = Double.parseDouble(txtRopa.getText());
    double salud = Double.parseDouble(txtSalud.getText());
    double transporte = Double.parseDouble(txtTransporte.getText());
    double vivienda = Double.parseDouble(txtVivienda.getText());

    // Registrar éxito en el parsing de los valores
    logger.info("Valores de entrada validados correctamente.");

    // Crear el DAO de CategoriaGasto con la conexión existente
    Connection conexion = ConexionDB.getConexion();
    if (conexion == null) {
        logger.severe("No se pudo establecer conexión con la base de datos.");
        JOptionPane.showMessageDialog(this, "Error al conectar con la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    logger.info("Conexión a la base de datos establecida.");

    CategoriaGastoDAOImpl categoriaGastoDAO = new CategoriaGastoDAOImpl(conexion);

    // Actualizar cada categoría en la base de datos
    categoriaGastoDAO.updateCategoriaGasto("Alimentación", alimentacion);
    logger.info("Categoría 'Alimentación' actualizada a: " + alimentacion);

    categoriaGastoDAO.updateCategoriaGasto("Deudas y préstamos", deudas);
    logger.info("Categoría 'Deudas y préstamos' actualizada a: " + deudas);

    categoriaGastoDAO.updateCategoriaGasto("Educación", educacion);
    logger.info("Categoría 'Educación' actualizada a: " + educacion);

    categoriaGastoDAO.updateCategoriaGasto("Entretenimiento", entretenimiento);
    logger.info("Categoría 'Entretenimiento' actualizada a: " + entretenimiento);

    categoriaGastoDAO.updateCategoriaGasto("Donaciones y regalos", regalos);
    logger.info("Categoría 'Donaciones y regalos' actualizada a: " + regalos);

    categoriaGastoDAO.updateCategoriaGasto("Ropa y accesorios", ropa);
    logger.info("Categoría 'Ropa y accesorios' actualizada a: " + ropa);

    categoriaGastoDAO.updateCategoriaGasto("Salud", salud);
    logger.info("Categoría 'Salud' actualizada a: " + salud);

    categoriaGastoDAO.updateCategoriaGasto("Transporte", transporte);
    logger.info("Categoría 'Transporte' actualizada a: " + transporte);

    categoriaGastoDAO.updateCategoriaGasto("Vivienda", vivienda);
    logger.info("Categoría 'Vivienda' actualizada a: " + vivienda);

    // Limpiar los campos de texto después de actualizar
    txtAlimentacion.setText("");
    txtDeudas.setText("");
    txtEducacion.setText("");
    txtEntretenimiento.setText("");
    txtRegalos.setText("");
    txtRopa.setText("");
    txtSalud.setText("");
    txtTransporte.setText("");
    txtVivienda.setText("");

    // Registrar éxito de la operación
    logger.info("Todas las categorías fueron actualizadas correctamente.");

    // Mostrar un mensaje de éxito
    JOptionPane.showMessageDialog(this, "Categorías actualizadas exitosamente.");
} catch (NumberFormatException e) {
    // Registrar error en el parsing de valores numéricos
    Logger.getLogger("CategoriaGastoUpdater").log(Level.WARNING, "Error en el formato numérico: ", e);
    JOptionPane.showMessageDialog(this, "Por favor, ingresa valores numéricos válidos.", "Error", JOptionPane.ERROR_MESSAGE);
} catch (Exception e) {
    // Registrar error inesperado
    Logger.getLogger("CategoriaGastoUpdater").log(Level.SEVERE, "Error inesperado: ", e);
    JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
establecerPresupuesto();

    }//GEN-LAST:event_bntModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstablecerPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstablecerPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstablecerPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstablecerPresupuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstablecerPresupuesto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt1Alimentacion;
    private javax.swing.JLabel txt1DeudasPrestamos;
    private javax.swing.JLabel txt1DonacionesRegalos;
    private javax.swing.JLabel txt1Educacion;
    private javax.swing.JLabel txt1Entretenimiento;
    private javax.swing.JLabel txt1RopaYaccesorios;
    private javax.swing.JLabel txt1Salud;
    private javax.swing.JLabel txt1Transporte;
    private javax.swing.JLabel txt1Vivienda;
    private javax.swing.JTextField txtAlimentacion;
    private javax.swing.JTextField txtDeudas;
    private javax.swing.JTextField txtEducacion;
    private javax.swing.JTextField txtEntretenimiento;
    private javax.swing.JTextField txtRegalos;
    private javax.swing.JTextField txtRopa;
    private javax.swing.JTextField txtSalud;
    private javax.swing.JTextField txtTransporte;
    private javax.swing.JTextField txtVivienda;
    // End of variables declaration//GEN-END:variables
}
